services:
  redis:
    image: redis:7-alpine
    container_name: secure_dedup_redis
    restart: unless-stopped
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports:
      - "6379:6379"

  localstack:
    image: localstack/localstack:latest
    container_name: secure_dedup_localstack
    restart: unless-stopped
    environment:
      SERVICES: s3
      AWS_DEFAULT_REGION: us-east-1
      DEBUG: 0
    ports:
      - "4566:4566"
    volumes:
      - localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  app:
    build:
      context: .
    container_name: secure_dedup_app
    restart: unless-stopped
    depends_on:
      - redis
      - localstack
    environment:
      PORT: 8000
      DEMO_MODE: "true"
      REQUIRE_API_KEY: "false"
      CHUNK_ENCRYPTION_DEFAULT_ON: "true"
      DEDUP_FINGERPRINT_MODE: secret_hmac
      DEDUP_FINGERPRINT_DEFAULT_ON: "true"
      STORAGE_BACKEND: localstack
      LOCALSTACK_ENDPOINT: http://localstack:4566
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: us-east-1
      S3_BUCKET: chunks
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MODEL_DIR: advanced_artifacts
      TELEMETRY_DB: /tmp/telemetry.db
      LOCAL_CHUNK_DIR: /tmp/local_chunks
    ports:
      - "8000:8000"

volumes:
  localstack_data:
