services:
  redis:
    image: redis:7-alpine
    container_name: secure_dedup_redis
    restart: unless-stopped
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports:
      - "6379:6379"

  localstack:
    image: localstack/localstack:latest
    container_name: secure_dedup_localstack
    restart: unless-stopped
    environment:
      SERVICES: s3
      AWS_DEFAULT_REGION: us-east-1
      DEBUG: 0
    ports:
      - "4566:4566"
    volumes:
      - localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  localstack_data:
